// Generated by CodiumAI

import Grammar from '../../src/grammars/grammar';
import MssqlGrammar from '../../src/grammars/mssql.grammar';

describe('MssqlGrammar', () => {
    // mssqlGrammar extends Grammar
    it('should extend Grammar', () => {
        const mssqlGrammar = new MssqlGrammar();
        expect(mssqlGrammar instanceof Grammar).toBe(true);
    });

    // Should have a '@instanceOf' property with a unique symbol
    it("should have a '@instanceOf' property with a unique symbol", () => {
        const mssqlGrammar = new MssqlGrammar();
        expect(mssqlGrammar['@instanceOf']).toBe(Symbol.for('MssqlGrammar'));
    });
});
