// Generated by CodiumAI

import Grammar from '../../src/grammars/grammar';
import MysqlGrammar from '../../src/grammars/mysql.grammar';

describe('MysqlGrammar', () => {
    // mysqlGrammar extends Grammar
    it('should extend Grammar', () => {
        const mysqlGrammar = new MysqlGrammar();
        expect(mysqlGrammar instanceof Grammar).toBe(true);
    });

    // Should have a '@instanceOf' property with a unique symbol
    it("should have a '@instanceOf' property with a unique symbol", () => {
        const mysqlGrammar = new MysqlGrammar();
        expect(mysqlGrammar['@instanceOf']).toBe(Symbol.for('MysqlGrammar'));
    });
});
