// Generated by CodiumAI

import Grammar from '../../src/grammars/grammar';
import PostgresGrammar from '../../src/grammars/postgres/postgres.grammar';

describe('PostgresGrammar', () => {
    // PostgresGrammar extends Grammar
    it('should extend Grammar', () => {
        const postgresGrammar = new PostgresGrammar();
        expect(postgresGrammar instanceof Grammar).toBe(true);
    });

    // Should have a '@instanceOf' property with a unique symbol
    it("should have a '@instanceOf' property with a unique symbol", () => {
        const postgresGrammar = new PostgresGrammar();
        expect(postgresGrammar['@instanceOf']).toBe(Symbol.for('PostgresGrammar'));
    });
});
